server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/seckill?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci
    username: seckill
    password: seckill
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: "ChangeMe_To_A_Long_Random_String_At_Least_32Chars"
    expireSeconds: 7200

seckill:
  stream:
    key: "stream:seckill:orders"
    dlqKey: "stream:seckill:orders:dlq"
    group: "g1"
    consumer: "c1"
  consumer:
    maxRetry: 5
  orderStatus:
    ttlSeconds: 3600
  cache:
    productTtlSeconds: 30
    nullTtlSeconds: 5
  rateLimit:
    # ???????? 5 ???????
    perUserPerSecond: 5